# Generated by Django 3.2.5 on 2021-09-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_user_is_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=48, verbose_name='Business Type')),
            ],
            options={
                'ordering': ('business_type',),
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category', models.CharField(max_length=48, verbose_name='Menu Category')),
            ],
            options={
                'ordering': ('menu_category',),
            },
        ),
        migrations.CreateModel(
            name='MenuSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_subcategory', models.CharField(max_length=48, verbose_name='Menu Subcategory')),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.menucategory', verbose_name='Menu Category Name')),
            ],
            options={
                'ordering': ('menu_category', 'menu_subcategory'),
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_category', models.CharField(max_length=48, unique=True, verbose_name='Business Category')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businesstype', verbose_name='Business Type')),
            ],
            options={
                'verbose_name_plural': 'Business categories',
                'ordering': ('business_type', 'business_category'),
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('display_name', models.CharField(default='Display Name', max_length=254)),
                ('banner_image', models.ImageField(null=True, unique=True, upload_to='')),
                ('business_name', models.CharField(default='Business Name', max_length=254)),
                ('contact_firstname', models.CharField(default='Contact First Name', max_length=254)),
                ('contact_lastname', models.CharField(default='Contact First Name', max_length=254)),
                ('address_1', models.CharField(default='Address 1', max_length=254)),
                ('address_2', models.CharField(blank=True, default='Address 2', max_length=254)),
                ('postal_code', models.CharField(default='Postal Code', max_length=6)),
                ('city', models.CharField(default='City', max_length=254)),
                ('contact_number', models.CharField(default='Contact Number', max_length=15)),
                ('VAT_number', models.CharField(default='VAT Number', max_length=12)),
                ('bankaccount_number', models.CharField(default='Bank Account Number', max_length=16)),
                ('business_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businesscategory')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businesstype')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
    ]
