# Generated by Django 3.2.5 on 2021-09-10 10:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0003_auto_20210909_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='business',
            new_name='BusinessDetails',
        ),
    ]
