# Generated by Django 3.2.5 on 2021-09-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_customer_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_company_user',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BusinessUser',
        ),
    ]
